dist: bionic
language: python
python:
  - "3.6"

env:
  global:
  - PYTHONPATH="/opt/drake/lib/python3.6/site-packages"
  matrix:
  - DRAKE_URL="https://drake-packages.csail.mit.edu/drake/nightly/drake-20201222-bionic.tar.gz"

install:
  - curl -o drake.tar.gz $DRAKE_URL && sudo tar -xzf drake.tar.gz -C /opt
  - yes | sudo /opt/drake/share/drake/setup/install_prereqs
  - pip install -r requirements.txt
  - pip install /opt/drake/share/drake/setup/requirements.txt

script:
  - pytest .
